# PANDAS ASSIGNMENTS

# import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

# Create a variable a = pd.Series([100,200,300,400])

In [2]:
a = pd.Series([100, 200, 300, 400])

# Print a, and data type

In [3]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

# Using indexing access the element 300 from the series a.

In [4]:
print(a.iloc[2])

300

# What are the values of index for series a?

In [5]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

# Change the index to ['c', 'a', 'b', 'd']

In [6]:
a.index = ['c', 'a', 'b', 'd']

# Access the value in the series with index 'd'

In [7]:
print(a['d'])

400

# Sort the values wrt to the index and print it

In [9]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

# Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [10]:
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

# Append b series at the end of the series

In [11]:
a = pd.concat([a, b])

# print a again after appending b into it

In [12]:
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])
a = pd.concat([a, b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
e    800
f    450
g    100
dtype: int64

# Sort the values in descending order of a and print the index of the sorted series

In [13]:
sorted_a = a.sort_values(ascending=False)
print(sorted_a.index)

Index(['e', 'e', 'f', 'f', 'd', 'b', 'a', 'c', 'g', 'g'], dtype='object')

# Pandas DataFrame

# Part 1

# Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [14]:
df = a.to_frame()
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100
e  800
f  450
g  100

# What is the shape of the datafarme
# (also, what does it imply?)

In [15]:
print(df.shape)
print("Shape means (rows, columns).")

(10, 1)
Shape means (rows, columns).

# Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

# What is the index of the dataframe, is it same as the series 'a'

In [16]:
print(df.index)
print(df.index.equals(a.index))

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g', 'e', 'f', 'g'], dtype='object')
True

# print the head and tail of the dataframe.
# Additional - (what does head and tali represent?)

In [17]:
print(df.head())
print(df.tail())

     0
c  100
a  200
b  300
d  400
e  800
     0
f  450
g  100
e  800
f  450
g  100

# Rename the column of the dataframes as 'points'

In [18]:
df.columns = ['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100
e     800
f     450
g     100

# Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple]

In [25]:
fruits_array = np.random.choice(['orange', 'mango', 'apple'], size=7)

# Create series fruits out of fruits array

In [31]:
 #fruits = pd.Series(fruits_array)

# Change the index of fruits to the index of dataframe df

In [32]:
fruits = pd.Series(fruits_array, index=df.index[:7])

# Add this fruits series as a new column to the dataframe df

In [33]:
df['fruits'] = fruits
print(df.head())

   points fruits
c     100  apple
a     200  mango
b     300  mango
d     400  mango
e     800  apple

# Pandas Concatenation
# Create a dataframe d1 where the cols are 'city' : ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ] and 'Temperature' : [15, 22, 20, 26,-2]

In [34]:
d1 = pd.DataFrame({'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'], 'Temperature': [15, 22, 20, 26, -2]})

# Print(d1)

In [35]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

# What is the shape of d1

In [36]:
print(d1.shape)

(5, 2)

# Set city= d1['city']

In [37]:
city = d1['city']

# Print city
# What is the type of city

In [38]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

# Create another datafeame 'd2' where the columns are 'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] 'Temperature' - [24,35,36,39]

In [39]:
d2 = pd.DataFrame({'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'], 'Temperature': [24, 35, 36, 39]})

# Print the shape of this dataframe

In [40]:
print(d2.shape)

(4, 2)

# merge the two dataframe together,save it in a new dataframe names 'd3'

In [41]:
d3 = pd.concat([d1, d2], ignore_index=True)
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

# Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20
# How many cities are there?

In [42]:
temp_le_20 = d3[d3['Temperature'] <= 20]
print(temp_le_20)
print('Number of cities:', len(temp_le_20))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities: 3

# Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [43]:
print(d3[d3['Temperature'] >= 35])

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

# Applying functions to columns and creating new columns

# We need to create another column in d3, which contains a boolean value for each city to indicate whether it's a union territory or not.

# . HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [44]:
def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [46]:
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

# The temperatures mentioned in 'Temperature' column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

# HINT -

# . Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
# . To check: c_to_f(10) should return 50.

In [47]:
def c_to_f(temp):
    return (temp * 9/5) + 32

In [48]:
print(c_to_f(10))

50.0

In [53]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
print(d3.columns)
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)

Index(['city', 'Temperature', 'is_ut'], dtype='object')

# Indexing and selecting rows in DataFrame

# Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [54]:
print(d1[d1['city'].isin(['Chandigarh', 'Delhi', 'Pondicherry'])])

         city  Temperature
0  Chandigarh           15
1       Delhi           22

# Select a subset of the dataframe d1 such that it contains the cities which only hav temperature above 90 Farenhiet.

In [55]:
print(d1[c_to_f(d1['Temperature']) > 90])

Empty DataFrame
Columns: [city, Temperature]
Index: []

# Select only the first three rows of the dataframe d1

In [56]:
print(d1.iloc[:3])

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

# Select all the rows and last two columns in the dataframe

In [57]:
print(d1.iloc[:, -2:])

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

# Groupby

In [58]:
# Create a dataframe using dictionary of your choice
data = {
    'name': ['Abhi', 'Rahul', 'Arun'],
    'age': [22, 23, 21],
    'city': ['Kerala', 'Delhi', 'Mumbai']
}

df = pd.DataFrame(data)

In [59]:
# Use Groupby of single column with aggregate sum()
df.groupby('city').sum()

         name  age
city
Delhi   Rahul   23
Kerala   Abhi   22
Mumbai   Arun   21

In [60]:
# Use Groupby of single column with aggregate count()
df.groupby('city').count()

        name  age
city
Delhi      1    1
Kerala     1    1
Mumbai     1    1

In [61]:
# Use Groupby of single column with aggregate min() and max()
df.groupby('city').agg(['min', 'max'])

         name        age
          min    max min max
city
Delhi   Rahul  Rahul  23  23
Kerala   Abhi   Abhi  22  22
Mumbai   Arun   Arun  21  21

In [62]:
# Use Groupby of any 2 columns with aggregate mean()
df.groupby(['city', 'name']).mean(numeric_only=True)

               age
city   name
Delhi  Rahul  23.0
Kerala Abhi   22.0
Mumbai Arun   21.0

In [63]:
# Use Groupby of any 2 columns with aggregate min() and max()
df.groupby(['city', 'name']).agg(['min', 'max'])

             age
             min max
city   name
Delhi  Rahul  23  23
Kerala Abhi   22  22
Mumbai Arun   21  21

# Data Range

# Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [64]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

# Print a

In [65]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

# What is the len of a?

In [66]:
print(len(a))

457

# What is the type of a

In [67]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>